version: '2.1'

services:
  smt-server:
    build: .
    restart: always
    environment:
      PORT: 8102
    expose:
      - 8102
    ports:
      - 8102:8102
    logging:
      driver: journald
    volumes:
      - .:/app
    container_name: smt-server
    network_mode: bridge

  smt-server-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 8100
    ports:
      - 8100:8100
    restart: always
    logging:
      driver: journald
    depends_on:
     - smt-server
    environment:
      VIRTUAL_HOST: smt-server.stellarium-web.org
      VIRTUAL_PORT: 8100
      LETSENCRYPT_HOST: smt-server.stellarium-web.org
      LETSENCRYPT_EMAIL: contact@noctua-software.com
    container_name: smt-server-frontend
    network_mode: bridge
